name: "AI Reviewer"
description: "自动调用 AI Reviewer API"
author: "Your Name"
branding:
  icon: "bot"
  color: "blue"

inputs:
  llm_provider_api_key:
    description: "AI Reviewer API Key"
    required: true
  llm_provider:
    description: "AI Reviewer API PROVIDER"
    required: true
  api_url:
    description: "API 服务地址"
    required: false
    default: "https://ping-ai-reviewer.vercel.app/review/webhook"
  token:
    description: "GitHub 或 GitLab 访问 token"
    required: true

runs:
  using: "composite"  # 改为复合步骤，支持多命令
  steps:
    - name: 安装依赖
      shell: bash  # 使用 bash 执行命令
      run: npm install && npm run build # 安装 package.json 中的依赖（包括 node-fetch 等）
      working-directory: ${{ github.action_path }}  # 指定 Action 代码所在目录（关键）

    - name: 执行 AI 审查脚本
      shell: bash
      run: node dist/review.action.js  # 运行主脚本
      working-directory: ${{ github.action_path }}  # 同上，确保在 Action 目录执行
      env:  # 传递输入参数到脚本环境变量（如果脚本需要）
       LLM_PROVIDER_API_KEY: ${{ inputs.llm_provider_api_key }}
       LLM_PROVIDER: ${{ inputs.llm_provider }}
       PING_AI_REVIEWER_API_URL: ${{ inputs.api_url }}
       EXPLICIT_TOKEN: ${{ inputs.token }}  # 将 token 传递到环境变量