name: "AI Reviewer"
description: "自动调用 AI Reviewer API"
author: "Your Name"
branding:
  icon: "bot"
  color: "blue"

inputs:
  api_key:
    description: "AI Reviewer API Key"
    required: true
  api_url:
    description: "API 服务地址"
    required: false
    default: "https://ping-ai-reviewer.vercel.app/review/webhook"

runs:
  using: "node20"
  main: "dist/review.action.js"
